apiVersion: v2
name: simple-sport-news-service
description: Generic Helm chart for simple_sport_news microservices
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: simple_sport_news Team
    email: team@example.com
keywords:
  - simple-sport-news
  - sports
  - content-aggregation
  - microservices
  - fastapi
