apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{- include "simple-sport-news-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.containerPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "simple-sport-news-service.selectorLabels" . | nindent 4 }}
